clear;close all;clc;
load 'data.mat';
x = data(:,1:end-1);
y=data(:,end);
m = size(x, 1);
sel = randperm(m);
sel_train = sel(1:floor(m * 0.6));
sel_val = sel(floor(m*0.6) + 1:end);
x_train = x(sel_train,:);
y_train = y(sel_train);
x_val = x(sel_val,:);
y_val = y(sel_val);
C = 0.1;
model = svmTrain(x_train, y_train, C, @linearKernel);
save model.mat model;
p = svmPredict(model, x_train);
fprintf('Training Accuracy: %f\n', mean(double(p == y_train)) * 100);
p = svmPredict(model, x_val);
fprintf('Training Accuracy: %f\n', mean(double(p == y_val)) * 100);